### PR TITLE
Update gemfile.lock

### PR DESCRIPTION
**Pull request by jpherdi**

### CODE REVIEW

**Comment by The-Ludwig** [comment]
@jpherdi Is programm.html only auto-formatted?

**Comment by jpherdi** [comment]
@The-Ludwig no, I had to remove the last div. Because there was an issue detected by htmlproofer. As a result it got also auto-formatted... 🙈

**Review by The-Ludwig — DISMISSED** [review]

**Comment by The-Ludwig** [comment]
@jpherdi somebody needs to solve conflicts, but update lgtm :)

**Comment by jpherdi** [comment]
@The-Ludwig done.

**Comment by jpherdi** [comment]
We want to start contacting the companies. For this is would be nice, if the website is save again and up-to-date.

**Review by The-Ludwig — APPROVED** [review]

**Pull request merged**
